# Generated by Django 2.0.7 on 2019-07-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190712_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnquiz',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizQuestion'),
        ),
    ]
