# Generated by Django 2.0.7 on 2019-07-12 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quizquestion_questiontext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnquiz',
            name='content',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.learnQuiz'),
        ),
    ]
