# Generated by Django 2.0.7 on 2019-07-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
