# Generated by Django 2.0.7 on 2019-07-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190713_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
